Edit Information CSS, custom platform, profile picture
agiledev-students-fall2023/4-final-project-qr-code-generator-app pull request #103
Opened 2023-11-27 03:57 UTC by byroncjy

Updates EditInformation's CSS and adds custom platform functionality
Adjusts backend routes and tests to allow for this

Resolves #82
resolves #78

2023-11-27 04:53 UTC, SivanC requested changes
Pretty good, noticed that when you try to save a custom platform it will just revert to being the dropdown. Also, reason for not just puttiing "Custom Platform" in the dropdown? Seems like it would fix this issue. I don't think we need people to be able to change custom platform to other types via dropdown.

No need to add extra validation in the back-end, that's what the schemas are for, and the values have different names so that needs to be updated in the rest of the code.

CSS changes that would be good if you have time, not a priority since still looks usable on phone:
- Make all the things to touch bigger because fingers are imprecise (higher prio than everything else)
- - more padding between everything
- Center header
- Make name bigger/more central and pfp upload button smaller/out of the way more
- "Select platform" dropdown slightly wider than others
- Justify X button to right

2023-11-27 04:53 UTC, SivanC commented on back-end/platforms.js
> +    // // Authorized platform values
If not needed then delete

2023-11-27 04:53 UTC, SivanC commented on back-end/platforms.js
> +    const isValid = platformInformation.every(
We have platform schema for this actually, check my branch

2023-11-27 04:53 UTC, SivanC commented on back-end/platforms.js
> +        item.hasOwnProperty('platform') &&
the fields are `name` and `value`

2023-11-27 04:53 UTC, SivanC commented on front-end/src/EditInformation.js
> +            { platform: "", info: "", isCustom: true},
won't this break your validator?

2023-11-27 04:53 UTC, SivanC commented on front-end/src/EditInformation.js
> +		.map(({ platform, info }) => ({ platform, info }))
What does this do?

2023-11-27 23:19 UTC, byroncjy commented on back-end/platforms.js
> +    const isValid = platformInformation.every(
deleted

2023-11-27 23:20 UTC, byroncjy commented on back-end/platforms.js
> +    // // Authorized platform values
deleted

2023-11-27 23:23 UTC, byroncjy commented on back-end/platforms.js
> +        item.hasOwnProperty('platform') &&
yeah, this was based on the frontend request data

2023-11-27 23:24 UTC, byroncjy commented on front-end/src/EditInformation.js
> +		.map(({ platform, info }) => ({ platform, info }))
see above comment

2023-11-27 23:25 UTC, byroncjy commented on front-end/src/EditInformation.js
> +            { platform: "", info: "", isCustom: true},
it would but that is what the later code is for:
![image](https://github.com/agiledev-students-fall2023/4-final-project-qr-code-generator-app/assets/87872349/d903019c-bcb3-4ee7-991f-5718a79678c2)
it removes the isCustom field from the data sent to the backend, so it still passes validator

2023-11-28 04:47 UTC, byroncjy commented
> Pretty good, noticed that when you try to save a custom platform it will just revert to being the dropdown. Also, reason for not just putting "Custom Platform" in the dropdown? Seems like it would fix this issue. I don't think we need people to be able to change custom platform to other types via dropdown.
> 
Changed accordingly
> Picture upload doesn't work, not sure if it is supposed to or not
> 
Fixed to work/integrate with backend
> No need to add extra validation in the back-end, that's what the schemas are for, and the values have different names so that needs to be updated in the rest of the code.
> 
Validation deleted
Field names changed
> CSS changes that would be good if you have time, not a priority since still looks usable on phone:
> 
> * Make all the things to touch bigger because fingers are imprecise (higher prio than everything else css-wise)
> * more padding between everything
> * Center header
> * Make name bigger/more central and pfp upload button smaller/out of the way more
> * "Select platform" dropdown slightly wider than others
> * Justify X button to right
>
Done some of these, will do more if have time tomorrow

2023-11-28 04:48 UTC, byroncjy commented
Note that I also added fixes for profile picture functionality plus integration with backend

2023-11-28 17:15 UTC, XinranTaoAngela commented
looks good!

2023-11-28 17:45 UTC, merged