User id backend frontend
agiledev-students-fall2023/4-final-project-qr-code-generator-app pull request #139
Opened 2023-12-05 18:35 UTC by XinranTaoAngela

enabled frontend to display userID from protected route

2023-12-05 18:37 UTC, SivanC commented on back-end/authRoutes.js
> +    res.json({
add 200 status

2023-12-06 03:27 UTC, SivanC requested changes
Some unnecessary changes or adding semicolons that don't need to be added, also tests don't pass, but the route itself looks fine.

2023-12-06 03:27 UTC, SivanC commented on front-end/src/Header.js
just remember to restore this file with `git restore Header.js` when merging

2023-12-06 03:27 UTC, SivanC commented on back-end/authRoutes.js
unsure what all the changes in the login route are, and lots of semicolons have been added

2023-12-06 03:27 UTC, SivanC commented on back-end/authRoutes.js
> +      message: `Hello ${user.first_name} ${user.last_name}`,
purpose of the message?

2023-12-06 03:27 UTC, SivanC commented on back-end/test/authroutes.test.js
> +const { app} = require('../app');
inconsistent spacing, and no need for brackets if its the only export

2023-12-06 03:27 UTC, SivanC commented on front-end/src/Header.css
restore this too

2023-12-06 03:27 UTC, SivanC commented on back-end/test/authroutes.test.js
> +        .post('/api/signup') // Adjust the route path based on your Express routes
the route is just /signup right now

2023-12-06 04:46 UTC, XinranTaoAngela commented on back-end/authRoutes.js
> +      message: `Hello ${user.first_name} ${user.last_name}`,
deleted this message

2023-12-06 05:08 UTC, SivanC approved these changes

2023-12-06 05:08 UTC, merged