Login sing up hone header footer
agiledev-students-fall2023/4-final-project-qr-code-generator-app pull request #29
Opened 2023-10-23 00:56 UTC by XinranTaoAngela

I edit the home page image, and also format the code with eslint/config

2023-10-23 14:54 UTC, SivanC commented on front-end/src/Footer.js
> +                <a href="/contact-us">Contact Us</a>
These should be React <Link>s, see slides

2023-10-23 14:55 UTC, SivanC commented on front-end/src/Header.css
> +.back-btn, .logout-btn {
In the other PR we have expanded all `btn` abbreviations to `button`, so when you merge just go with that, don't have to edit anything on your branch (assuming it's after Byron).

2023-10-23 14:59 UTC, SivanC commented on front-end/src/HomeScreen.js
> +          <a href="/generate-code" className="home-link">Generate Code</a>
This will also be `select-information`, again don't have to change here but go with that when resolving merge conflicts.

2023-10-23 15:01 UTC, SivanC requested changes
Looks pretty good, only big thing to worry about before merging is changing how the image is grabbed. Let me know if you understand what I'm talking about with resolving merge conflicts with Byron's PR, if not I can explain more.

2023-10-23 15:07 UTC, SivanC commented
Also make sure to mention the closed issues in your description.

2023-10-23 15:11 UTC, SivanC commented on front-end/src/Login.js
> +import { Navigate, useNavigate } from 'react-router-dom';
This line is giving an unused var error in ESLint

2023-10-24 02:21 UTC, XinranTaoAngela commented on front-end/src/HomeScreen.js
> +          <img src = 'https://picsum.photos/400' alt="App Logo" className="app-logo" />
edited

2023-10-26 01:46 UTC, merged