front-end for SavedConnections page
agiledev-students-fall2023/4-final-project-qr-code-generator-app pull request #32
Opened 2023-10-24 17:37 UTC by larahynkim

2023-10-24 17:42 UTC, XinranTaoAngela commented on front-end/src/SavedConnections.js
> +    { id: 1, name: 'John Doe' },
I think for now we need to mock data that will be pulled from the backend using Mockaroo, Sivan mentioned in the chat on how to use that, you can also look at the master branch and my PR for references

2023-10-25 15:55 UTC, XinranTaoAngela requested changes
Hi! over all very nice, you need some minor changes, let us know in the chat if theres anything uncertain!

2023-10-26 11:56 UTC, larahynkim commented on front-end/src/SavedConnections.js
> +      <div className="connections-grid">
thanks for the feedback! i saw in app.js of the master that the header and footer components are rendered globally across all pages. bc of this, i don't think we have to add the header and footer to each of the pages ??  but lmk if i'm wrong!

2023-10-26 15:39 UTC, SivanC commented on front-end/src/SavedConnections.css
> +.sc-header {
try to keep all the class names unabbreviated

2023-10-26 16:06 UTC, larahynkim commented on front-end/src/SavedConnections.css
> +.sc-header {
thanks! just made the revisions with all of your suggestions

2023-10-26 16:16 UTC, Pan-LLi approved these changes

2023-10-26 16:18 UTC, XinranTaoAngela approved these changes

2023-10-26 16:24 UTC, merged