Backend Saved Connections
agiledev-students-fall2023/4-final-project-qr-code-generator-app pull request #53
Opened 2023-11-08 08:23 UTC by larahynkim

2023-11-08 19:51 UTC, SivanC requested changes
Lara since this is your PR I mostly just addressed the changes you made and not so much Byron's. Looking good overall, just need to add a couple tests and also get your API information from the .env file instead of inside the code. Let me know if you have questions.
--Sivan

2023-11-08 19:51 UTC, SivanC commented on back-end/users.js
> +    const { email, first_name: firstName, last_name: lastName, url_picture: urlPicture } = req.body
no key for email?

2023-11-08 19:51 UTC, SivanC commented on front-end/src/ConnectionDetails.js
> +        const response = await axios.get(`http://localhost:3001/api/connection-details/${id}`);
I think we are supposed to access this URL through the .env file?

2023-11-08 19:51 UTC, SivanC commented on front-end/src/SavedConnections.js
> +        const response = await axios.get('http://localhost:3001/api/saved-connections');
Should also be fetched from .env

2023-11-08 19:51 UTC, SivanC commented on back-end/connections.js
> +    const mockApiUrl = 'https://api.mockaroo.com/api/1a199910?count=16&key=14ea8470';
get from .env file

2023-11-08 19:51 UTC, SivanC commented on back-end/test/connections.test.js
> +    it('it should GET all the connections', (done) => {
I think you need to test:
- When the request is successful, does it return the expected data
- When the request is not successful, does it behave appropriately
- Does the request fail/succeed as expected, i.e. is it failing where it should fail and succeeding where it should succeed?

Ultimately you can't guarantee that it won't fail, you just want to make sure that no matter what it is doing what you expect.

Also I think you don't need to write 'it' again, but ultimately inconsequential.

2023-11-08 19:55 UTC, SivanC commented on back-end/test/connections.test.js
Also maybe rename to connections-test.js?

2023-11-08 20:19 UTC, larahynkim commented on front-end/src/ConnectionDetails.js
> +        const response = await axios.get(`http://localhost:3001/api/connection-details/${id}`);
I wasn't responsible for the ConnectionDetails page, should I still try to fix it or should I leave it?

2023-11-08 22:04 UTC, SivanC commented on front-end/src/ConnectionDetails.js
> +        const logoUrl = 'https://picsum.photos/200/300';
I think we'll need to grab profile pictures through a route no?

2023-11-13 04:06 UTC, Pan-LLi commented
Hi Lara, I run your code on CodeSpace, it seems that fetching data in your SavedConnections.js is not working. Can you check that?

2023-11-13 04:45 UTC, Pan-LLi commented
You can edit your CSS style of displaying different connections, when the connection goes out of screen/browser size when setting the page to size of the phone.

2023-11-13 17:16 UTC, merged