Connection details backend
agiledev-students-fall2023/4-final-project-qr-code-generator-app pull request #61
Opened 2023-11-13 20:08 UTC by Pan-LLi

2023-11-13 23:45 UTC, SivanC requested changes
Good start but definitely needs some work before it can be pushed to master. Aside from my specific comments, you seem to have changed a lot of files by replacing 2-width indents with 4-width, so if you can change them back to how they were that would be great. Keep it up!

2023-11-13 23:45 UTC, SivanC commented on back-end/ConnectionDetails.js
For the backend files you should use lowercase file names, it can be a little confusing for them to have exactly the same name as on front end.

2023-11-13 23:45 UTC, SivanC commented on back-end/ConnectionDetails.js
> +  // 'https://my.api.mockaroo.com/QRcodeResult.json?key=723ed310'
this should be grabbed from the .env file

2023-11-13 23:45 UTC, SivanC commented on back-end/ConnectionDetails.js
> +  } catch (error) {
you should still return something here, usually status code + error message, see others' files to get an idea.

2023-11-13 23:45 UTC, SivanC commented on back-end/app.js
In this file you should add a couple lines like you see at the bottom that preface your `/ScanCode` path to give it a little more separation. This enables things like using an id in a user path, because you can write `xxx/users/id`, otherwise `xxx/yyy` would be ambiguously an id or some other path (`xxx/42` vs. `xxx/hi` for example)

2023-11-13 23:45 UTC, SivanC commented on back-end/package.json
> -  "main": "server.js",
why remove this?

2023-11-13 23:45 UTC, SivanC commented on back-end/server.js
> +  res.json({ LogoUrl })
why add these routes here? they're already in your other file

2023-11-13 23:45 UTC, SivanC commented on back-end/test/testConnectionDetails.js
As of right now there is an exception when running your tests, needs to be fixed so you can make sure they pass. Furthermore, you should not just be testing for success but also failure. Not as important right now so I wouldn't require you to do it before merging but later we want to make sure that if we don't get the response that everything works as expected.

2023-11-13 23:45 UTC, SivanC commented on back-end/test/testConnectionDetails.js
> +      .send({ qrCodeText: 'https://my.api.mockaroo.com/QRcodeResult.json?key=723ed310' })
Again needs to be grabbed from the .env file

2023-11-13 23:45 UTC, SivanC commented on front-end/src/ConnectionDetails.js
Getting an error when navigating here

2023-11-14 00:31 UTC, Pan-LLi commented on back-end/test/testConnectionDetails.js
> +      .send({ qrCodeText: 'https://my.api.mockaroo.com/QRcodeResult.json?key=723ed310' })
fixed

2023-11-14 00:39 UTC, Pan-LLi commented on back-end/ConnectionDetails.js
> +  } catch (error) {
Fixed

2023-11-14 00:53 UTC, Pan-LLi commented on back-end/ConnectionDetails.js
Fixed

2023-11-14 06:12 UTC, Pan-LLi commented on back-end/test/testConnectionDetails.js
Fixed. I'll take care of failure case later

2023-11-14 06:17 UTC, Pan-LLi commented on front-end/src/ConnectionDetails.js
Please use the QR code I provided to navigate from ScanCode to ConnectionDetails

2023-11-14 06:18 UTC, Pan-LLi commented on back-end/server.js
> +  res.json({ LogoUrl })
I'm leaving it like this because the image data will be get like this when database is added

2023-11-14 14:55 UTC, SivanC requested changes
Sorry but it's still not working for me. A lot of good changes but I can't approve because it still crashes. Here's some things to fix:
- The backend server doesn't start, both because your ConnectionDetails.js file is misnamed and because it complains that the port its using is busy.
- I still get a blank screen on `/ConnectionDetails/<id>` and an error on `/ConnectionDetails` (location.state is null) with proper .env files
- Your tests do not complete for me either, probably because the server can't start
- You added a lot of semicolons unnecessarily to many lines

2023-11-14 14:55 UTC, SivanC commented on back-end/ConnectionDetails.js
> +  } catch (error) {
it doesn't look like anything changed?

2023-11-14 14:55 UTC, SivanC commented on back-end/test/testConnectionDetails.js
getting errors still

2023-11-14 18:14 UTC, larahynkim requested changes
when i try to run your code, it crashes. i tried to fix the errors on my computers, and added comments below about how to fix those errors. for some reason, the connection details page still won't load.

2023-11-14 18:14 UTC, larahynkim commented on back-end/ConnectionDetails.js
> +module.exports = app;
you have to do module.exports = router; not module.exports = app; bc u have to export it as a router

2023-11-14 18:14 UTC, larahynkim commented on back-end/ConnectionDetails.js
> +
include const router = express.Router();
bc again, you have to export as router

2023-11-14 18:14 UTC, larahynkim commented on back-end/app.js
> +const connectionsdetailsRoutes = require('./connectionsdetails');
connectionsdetails is not the name of your file- it's ConnectionDetails. also, Node.js is case sensitive, so you have to match the case exactly. It should be require('./ConnectionDetails') if your file is named 'ConnectionDetails.js'.

2023-11-14 18:14 UTC, larahynkim commented on back-end/ConnectionDetails.js
> +const jsQR = require('jsqr');
if you're going to use the jsqr module in your code, maybe we should add in our instructions to run the command, 
npm install jsqr,
because i wasn't able to run the code without doing it.

2023-11-14 18:14 UTC, larahynkim commented on back-end/ConnectionDetails.js
> +
I think you have to delete lines 58-61, because this is already done in server.js, so since there are multiple listen calls, the app starts multiple servers, both 5002 and 3001

2023-11-14 18:14 UTC, larahynkim commented on front-end/src/ConnectionDetails.js
> +	}, []);
in between the [], add in qrCodeText 
you have to add it in the dependency array, there's an eslint error

2023-11-15 16:15 UTC, merged